Repository micronaut-projects/micronaut-jmx, pull requests merged in 2020-09, with the labels that each got.

#37 doc: Add release history section
  build.gradle
  jmx/build.gradle
  src/main/docs/guide/releaseHistory.adoc
  src/main/docs/guide/toc.yml
Labels: relates-to: build, type: docs

#40 [jmx] Update common files for branch master
  .github/workflows/gradle.yml
Labels: relates-to: build

#41 bump up micronaut test to 2.0.0
  gradle.properties
Labels: type: dependency-upgrade
